os:
  - Visual Studio 2017

environment:
  matrix:
  - TOOLSET: vs2017

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive
  - bin\windows\genie %TOOLSET%

build:
  project: build/projects/$(TOOLSET)/toy.sln
